services:
  dynamic-pricing-app:
    build: .
    container_name: dynamic-pricing-app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
