[server]
headless = true
runOnSave = true
enableCORS = false
maxMessageSize = 500
port = 8501

[client]
toolbarMode = "minimal"
showSidebarNavigation = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[theme]
base = "light"
primaryColor = "#0d6efd"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#212529"
font = "sans serif"