[server]
headless = true
runOnSave = true
enableCORS = false
maxMessageSize = 500
port = 8501

[client]
toolbarMode = "minimal"
showSidebarNavigation = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"
server.headless = true